### ISSUE TITLE
Union

### ISSUE THREAD

**Issue by Reekin** [Henkoglobin/lazylualinq#5]
Is there a method to flatten a nested table？

**Comment by Henkoglobin** [comment]
Hey there! 

I see that you answered your own question, but you've motivated me to work on the documentation for a bit, so basically all the relevant phrases (nested, flatten, flatMap, etc) should now be there to find selectMany. Hope this is helpful (to you and/or others that may have the same problem in the future).

Thanks for using lazylualinq!

**Comment by Reekin** [comment]
Aha that's great, thank you!
